language: python
python:
  - "2.7"

before_install:
  - pip install coverage
  - pip install python-coveralls

install: "pip install -r requirements.txt"

script: nosetests --with-doctest --with-coverage --cover-package=nodepy;

after_success:
  - coveralls
