language: python
python:
  - "2.7"

before_install:
  - pip install coverage
  - pip install python-coveralls

install: "pip install -r requirements.txt"

script: coverage run --source=nodepy tests.py

after_success:
  - coveralls
