name: nodepy

channels:
    - anaconda

dependencies:
    - python==3.7
    - pip:
        - matplotlib
        - pyyaml
        - sphinxcontrib-bibtex
        - networkx
        - numpy
        - sympy
